### ISSUE TITLE
Support override default flume archive URL attribute in the resource

### ISSUE THREAD

**Issue by jeffzjd** [jrh3k5/flume-agent-cookbook#19]
To give the consumer more flexibility over how a Flume agent can be installed, it would be desirable to support an option to allow the user to override the default flume archive URL attribute in the resource such that if not specified, it would fallback to the default attribute.

**Comment by jrh3k5** [comment]
Appropriately, I've got a TODO to document the availability of the configuration, but you should be able to override the default specified here:

https://github.com/jrh3k5/flume-agent-cookbook/blob/master/attributes/default.rb

Is that the functionality you're looking for?

**Comment by jrh3k5** [comment]
Or, rereading this, are you looking for an option in the resource definition itself to specify the URL?

**Comment by jeffzjd** [comment]
In the resource definition itself so that in a cookbook that can install multiple agents I can specify what Flume version each one of them should use.
